var items=[
    {
        "IDActivo": 42,
        "Referencia": "NPE-18-0006",
        "Numero": 6,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-21",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Madera - Distinta LER 200137",
        "Fabricante": "",
        "Serie": "LER 200138",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R1",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 32,
        "Referencia": "PEL-18-0003",
        "Numero": 3,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Envases Metalicos Contaminados",
        "Fabricante": "",
        "Serie": "LER 150110",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R4",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 43,
        "Referencia": "NPE-18-0007",
        "Numero": 7,
        "FechaAdquisicion": "2018-03-22",
        "FechaRegistro": "2018-03-22",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-06-27",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Pilas alcalinas",
        "Fabricante": "",
        "Serie": "LER 160604",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 33,
        "Referencia": "PEL-18-0004",
        "Numero": 4,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-06-27",
        "FechaProxRevision": "2025-12-26",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Envases Plasticos Contaminados",
        "Fabricante": "",
        "Serie": "LER 150110",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R4",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 44,
        "Referencia": "NPE-18-0008",
        "Numero": 8,
        "FechaAdquisicion": "2018-03-22",
        "FechaRegistro": "2018-03-22",
        "IDResponsableAdquisicion": null,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Tubos fluorescentes",
        "Fabricante": "",
        "Serie": "LER 200121",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 34,
        "Referencia": "PEL-18-0005",
        "Numero": 5,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Absorbentes",
        "Fabricante": "",
        "Serie": "LER 150202",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R1 y R13",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 45,
        "Referencia": "NPE-18-0009",
        "Numero": 9,
        "FechaAdquisicion": "2018-03-22",
        "FechaRegistro": "2018-03-22",
        "IDResponsableAdquisicion": 4,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 3,
        "Nombre": "Residuos Toner",
        "Fabricante": "",
        "Serie": "LER 080318",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 35,
        "Referencia": "PEL-18-0006",
        "Numero": 6,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Residuos de Pinturas",
        "Fabricante": "",
        "Serie": "LER 080111",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 53,
        "Referencia": "PEL-19-0008",
        "Numero": 8,
        "FechaAdquisicion": "2019-02-19",
        "FechaRegistro": "2019-02-21",
        "IDResponsableAdquisicion": 2145,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 0,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Filtros de cabina de pintura",
        "Fabricante": "Varios",
        "Serie": "LER 150202",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Código Tratamiento: R13 R1",
        "IDEstadoCalibrado": 0,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 2,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 0,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 0,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 0,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "Ultimo Cambio_ 02\/2019",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 36,
        "Referencia": "PEL-18-0007",
        "Numero": 7,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Aerosoles Vacios",
        "Fabricante": "",
        "Serie": "LER 150111",
        "Modelo": "",
        "MarcadoCE": 0,
        "OtrosCertificados": 0,
        "Observaciones": "Codigo Tratamiento: R13 y R4",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 37,
        "Referencia": "NPE-18-0004",
        "Numero": 4,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-02-20",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Papel y Carton",
        "Fabricante": "",
        "Serie": "LER 200101",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R5",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida bimensual de residuo",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 38,
        "Referencia": "NPE-18-0003",
        "Numero": 3,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-06-27",
        "FechaProxRevision": "2025-12-26",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Residuos Electricos",
        "Fabricante": "",
        "Serie": "LER 200136",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R5",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 39,
        "Referencia": "NPE-18-0001",
        "Numero": 1,
        "FechaAdquisicion": "2018-03-20",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 1138,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 1138,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Hierro y Acero",
        "Fabricante": "",
        "Serie": "LER 170405",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R4",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "No recogen si son menos de 1000Kg. Es un residuo No Peligroso, por tanto no hay que recogerlo cada 6 meses.",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 40,
        "Referencia": "NPE-18-0002",
        "Numero": 2,
        "FechaAdquisicion": "2018-03-20",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 1138,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-06-27",
        "FechaProxRevision": "2025-12-26",
        "IDRevisa": 0,
        "IDServicioTecnico": 1138,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Motores Electricos",
        "Fabricante": "",
        "Serie": "LER 160214",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R4",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 3,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "No recogen si son menos de 1000Kg. Es un residuo No Peligroso, por tanto no hay que recogerlo cada 6 meses.",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 30,
        "Referencia": "PEL-18-0001",
        "Numero": 1,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 31,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Aceites de Motor y Lubricantes",
        "Fabricante": "Varios",
        "Serie": "LER 130208",
        "Modelo": "",
        "MarcadoCE": 0,
        "OtrosCertificados": 0,
        "Observaciones": "Codigo Tratamiento: R13 y R9",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 41,
        "Referencia": "NPE-18-0005",
        "Numero": 5,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-21",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-02-20",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 29,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Plasticos Inertes",
        "Fabricante": "",
        "Serie": "LER 200139",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento:R13 y R1",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida bimensual de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "[22.04.21] Pte documentación correcta",
        "tpcod": "RES",
        "tcod": "NPE",
        "tpdescr": "Residuos",
        "tdescr": "No Peligrosos",
        "pord": 7
    },
    {
        "IDActivo": 31,
        "Referencia": "PEL-18-0002",
        "Numero": 2,
        "FechaAdquisicion": "2018-03-16",
        "FechaRegistro": "2018-03-20",
        "IDResponsableAdquisicion": 2144,
        "IDResponsableRevisionInterna": 3452,
        "TieneRevisionInterna": 1,
        "IDResponsableRevisionExterna": 3452,
        "TieneRevisionExterna": 1,
        "IDProveedor": 622,
        "IDCuentaContable": 0,
        "FechaUltimaRevision": "2025-12-19",
        "FechaProxRevision": "2026-06-19",
        "IDRevisa": 0,
        "IDServicioTecnico": 622,
        "IDTipoActivo": 28,
        "IDZona": 2,
        "IDEstado": 1,
        "IDEstadoPRL": 1,
        "Nombre": "Restos Disolventes",
        "Fabricante": "Varios",
        "Serie": "LER 140603",
        "Modelo": "",
        "MarcadoCE": 2,
        "OtrosCertificados": 2,
        "Observaciones": "Codigo Tratamiento: R13 y R2",
        "IDEstadoCalibrado": 3,
        "Calibracion": 0,
        "TipoCalibracion": 0,
        "CalibrarPor": 0,
        "ProximaCalibracion": "0000-00-00",
        "FechaCalibracion": "0000-00-00",
        "IDEmpresaCalibra": 0,
        "ValorReposicion": 0,
        "Borrado": 0,
        "ObservacionesPRL": "",
        "ObservacionesCalibrado": "Recogida semestral de residuos",
        "IDAutorizacion": 3,
        "FechaAutorizacion": "0000-00-00",
        "IDDocAutorizacion": 0,
        "IDManuales": 3,
        "FechaManuales": "0000-00-00",
        "IDDocManuales": 0,
        "IDInstrucciones": 0,
        "FechaInstrucciones": "0000-00-00",
        "IDDocInstrucciones": 0,
        "IDFormacion": 3,
        "FechaFormacion": "0000-00-00",
        "IDDocFormacion": 0,
        "IDEvaluacion": 3,
        "FechaEvaluacion": "0000-00-00",
        "IDDocEvaluacion": 0,
        "IDRiesgo": 0,
        "FechaRiesgo": "0000-00-00",
        "IDDocRiesgo": 0,
        "Notas": "",
        "tpcod": "RES",
        "tcod": "PEL",
        "tpdescr": "Residuos",
        "tdescr": "Peligrosos",
        "pord": 7
    }
]