// Link as http://erp/apps/sibre_erp.php?_op=GET_APPOBJS&w=rgpd&_jsx=RGPD

var RGPD={
    "1": {
        "IDCuenta": 1,
        "LenguajeCuenta": "ES",
        "Codigo": "",
        "Nombre": "Sibre Brakes Spain SL",
        "CIF": "B93045185",
        "Direccion": "P.I.Trévenez. C\/Actriz Amelia de la Torre, 3",
        "CP": "29004 ",
        "Poblacion": "Málaga",
        "Provincia": "Málaga",
        "Pais": "España",
        "IDZona": 1,
        "IDPais": 73,
        "Email": "",
        "Telefono": "952 203912",
        "Fax": "",
        "IDUsuarioAgente": null,
        "IDUsuarioResponsable": 1,
        "IDResponsableM": 4,
        "IDResponsableR": null,
        "IDEstado": 0,
        "FechaUltimaActualizacion": "2017-09-26",
        "FechaProximaActualizacion": null,
        "IDActualizacionEstado": 0,
        "FechaAlta": "2014-04-15",
        "Portal": "",
        "Usuario": null,
        "Clave": "",
        "Notas": "",
        "CondicionesCobro": "",
        "CondicionesBreve": "undefined",
        "OtrosCobro": "Cbn el pedido",
        "CondicionesPago": "",
        "NombreAbreviado": "SIBRE ES",
        "Web": "",
        "Actividad": "",
        "IDTipoCuenta": 0,
        "IDSector": 0,
        "CodigoCuenta": 1,
        "NotasSuperior": "CCC: 0111 29122943227",
        "IDTipoIva": null,
        "FiscalIDType": 0
    },
    "622": {
        "IDCuenta": 622,
        "LenguajeCuenta": "ES",
        "Codigo": "",
        "Nombre": "Ambar Remasur, SL",
        "CIF": "B29690138",
        "Direccion": "Pol. Ind. La Estrella, C\/ Benadalid, 42",
        "CP": 29006,
        "Poblacion": "Málaga",
        "Provincia": "Málaga",
        "Pais": "España",
        "IDZona": 1,
        "IDPais": 73,
        "Email": "remasur@ambarplus.com",
        "Telefono": "951742325 (952312076\/314751)",
        "Fax": "",
        "IDUsuarioAgente": 2182,
        "IDUsuarioResponsable": 4,
        "IDResponsableM": 3452,
        "IDResponsableR": null,
        "IDEstado": 5,
        "FechaUltimaActualizacion": "2026-03-19",
        "FechaProximaActualizacion": "2027-03-19",
        "IDActualizacionEstado": 3,
        "FechaAlta": "2016-02-16",
        "Portal": "https:\/\/comunidad.ambarplus.com\/s\/",
        "Usuario": 0,
        "Clave": "",
        "Notas": "Gestor AN 0036_ Gestor GRNP 47_ Gestor GRU-680-R\nCAIXA ES33 2100 4002 2622 0023 7886\nSADADELL ES02 0081 0587 3300 0141 4243\nBANKINTER ES45 0128 7702 9901 0000 5733\nSANTANDER ES27 0075 0818 6806 0366 4491\nIBERCAJA ES64 2085 9273 1303 3550 6141",
        "CondicionesCobro": "",
        "CondicionesBreve": "",
        "OtrosCobro": "Recibo domiciliado",
        "CondicionesPago": "",
        "NombreAbreviado": "Remasur",
        "Web": "https:\/\/comunidad.ambarplus.com",
        "Actividad": "",
        "IDTipoCuenta": 0,
        "IDSector": 7,
        "CodigoCuenta": 1,
        "NotasSuperior": "admin@sibre.remasur\nSibre.2023\n",
        "IDTipoIva": 2,
        "FiscalIDType": 0
    }
}